'use client'

import { useState, useMemo, useEffect } from 'react'
import { useRouter, useParams, useSearchParams } from 'next/navigation'
import { 
  StockDetailPanel, 
  STOCK_DATA,
  StockInfo
} from '@/components/trade/StockDetailPanel'
import { 
  MutualFundDetailPanel
} from '@/components/trade/MutualFundDetailPanel'
import { MutualFundInfo } from '@/types/account'
import { useAccountData } from '@/contexts/AccountDataContext'
import { TradeExecutionPanel } from '@/components/trade/TradeExecutionPanel'
import { AccountSelectionModal } from '@/components/trade/AccountSelectionModal'
import { SearchModal } from '@/components/trade/SearchModal'
import { WatchlistTable } from '@/components/trade/SearchAndWatchlist'
import { OptionsChainTable } from '@/components/trade/OptionsChainTable'
import { SecurityHeader } from '@/components/trade/SecurityHeader'
import { OptionTradeDetails } from '@/components/trade/OptionsChainTable'

type TradeMode = 'buy' | 'sell' | null

// Function to detect if a symbol is a mutual fund
const isMutualFund = (symbol: string): boolean => {
  const upperSymbol = symbol?.toUpperCase();
  return upperSymbol === 'VTSAX' || 
         upperSymbol === 'VFIAX' ||
         upperSymbol === 'VTSMX' ||
         // Add more mutual fund symbols as needed
         false;
};

export default function TradeSymbolPage() {
  const router = useRouter();
  const params = useParams();
  const searchParams = useSearchParams();
  const symbol = params?.symbol as string;
  const { data } = useAccountData();
  const marketData = data?.marketData;

  const stock = useMemo(() => {
    const upperSymbol = symbol?.toUpperCase();
    
    // Try to get real market data first
    const realMarketData = marketData?.find(m => m.symbol === upperSymbol);
    
    
    if (realMarketData) {
      // Create StockInfo from real market data
      const stockInfo: StockInfo = {
        name: realMarketData.description || `${upperSymbol} Inc.`,
        exchangeInfo: 'Nasdaq • USD',
        price: realMarketData.currentPrice || 0,
        change: realMarketData.dayChange || 0,
        changePercent: realMarketData.dayChangePercent || 0,
        peRatio: 30.5, // Mock PE ratio
        volume: realMarketData.volume || 0,
        chartData: {}, // Will be generated by StockDetailPanel
        marketStats: {
          open: realMarketData.open || 0,
          high: realMarketData.high || 0,
          low: realMarketData.low || 0,
          prevClose: realMarketData.previousClose || 0,
          '52W High': realMarketData.fiftyTwoWeekHigh || 0,
          '52W Low': realMarketData.fiftyTwoWeekLow || 0
        }
      };
      console.log('📊 TradePage - Created stockInfo:', stockInfo);
      return stockInfo;
    } else {
      console.log('❌ TradePage - No real market data found, using mock data for', upperSymbol);
      // Fallback to mock data if not found
      const mockData = STOCK_DATA[upperSymbol] || STOCK_DATA.AAPL;
      return mockData;
    }
  }, [symbol, marketData]);

  const mutualFund = useMemo(() => {
    const upperSymbol = symbol?.toUpperCase();
    
    // Only process if it's a mutual fund
    if (!isMutualFund(upperSymbol)) {
      return null;
    }
    
    
    // Try to get real market data first
    const realMarketData = marketData?.find(m => m.symbol === upperSymbol);
    
    if (realMarketData) {
      // Create MutualFundInfo from real market data
      const mutualFundInfo: MutualFundInfo = {
        symbol: upperSymbol,
        name: realMarketData.description || `${upperSymbol} Fund`,
        exchangeInfo: 'Mutual Fund - NAV • USD',
        nav: realMarketData.currentPrice || 0,
        change: realMarketData.dayChange || 0,
        changePercent: realMarketData.dayChangePercent || 0,
        expenseRatio: 0.03, // Default expense ratio
        minimumInvestment: 3000, // Default minimum
        chartData: {}, // Will be generated by MutualFundDetailPanel
        marketStats: {
          open: realMarketData.open || 0,
          high: realMarketData.high || 0,
          low: realMarketData.low || 0,
          prevClose: realMarketData.previousClose || 0,
          '52W High': realMarketData.fiftyTwoWeekHigh || 0,
          '52W Low': realMarketData.fiftyTwoWeekLow || 0,
          ytdReturn: 8.5, // Default YTD return
          totalAssets: 1000000000 // Default $1B
        },
        fundDetails: {
          previousClose: realMarketData.previousClose || 0,
          ytdReturn: 8.5, // Default YTD return
          expenseRatio: 0.03, // Default expense ratio
          category: 'US Equity Large Cap Blend', // Default category
          netAssets: 1.0, // Default $1B
          yield: 1.0, // Default 1% yield
          frontLoad: '-', // Default no load
          inceptionDate: '01 Jan 2000' // Default inception date
        }
      };
      return mutualFundInfo;
    } else {
      console.log('❌ TradePage - No real market data found, using mock data for mutual fund', upperSymbol);
      // Fallback to mock data if not found - return null to use default mock data in component
      return null;
    }
  }, [symbol, marketData]);
  
  const isPositive = stock ? stock.change >= 0 : false;
  const isMutualFundSymbol = isMutualFund(symbol);

  // Extract account ID from URL path
  const accountIdFromPath = params?.accountId as string;
  const [selectedAccountId, setSelectedAccountId] = useState<string | null>(accountIdFromPath || null);
  const [showAccountModal, setShowAccountModal] = useState(false);
  const [showSearchModal, setShowSearchModal] = useState(false);
  
  // Initialize trade mode from URL parameters
  const urlMode = searchParams?.get('mode');
  const initialTradeMode = urlMode === 'buy' || urlMode === 'sell' ? urlMode : null;
  const [currentTradeMode, setCurrentTradeMode] = useState<TradeMode>(initialTradeMode);
  
  
  // Initialize pageViewMode from URL parameters
  const urlType = searchParams?.get('type');
  const initialPageViewMode = urlType === 'options' ? 'options' : 'stock';
  const [pageViewMode, setPageViewMode] = useState<'stock' | 'options'>(initialPageViewMode);

  // Update pageViewMode when URL parameters change
  useEffect(() => {
    const currentUrlType = searchParams?.get('type');
    const newPageViewMode = currentUrlType === 'options' ? 'options' : 'stock';
    setPageViewMode(newPageViewMode);
  }, [searchParams]);

  // Update trade mode when URL parameters change
  useEffect(() => {
    const currentUrlMode = searchParams?.get('mode');
    const newTradeMode = currentUrlMode === 'buy' || currentUrlMode === 'sell' ? currentUrlMode : null;
    setCurrentTradeMode(newTradeMode);
  }, [searchParams]);

  // Update selected account ID when URL path changes (only if not already set)
  useEffect(() => {
    const newAccountId = params?.accountId as string;
    console.log('🔍 TradeSymbolPage - Account ID from URL:', newAccountId);
    if (newAccountId && newAccountId !== selectedAccountId) {
      setSelectedAccountId(newAccountId);
    }
  }, [params?.accountId, selectedAccountId]);



  const [isWatchlisted, setIsWatchlisted] = useState(false);
  const [currentOptionTradeDetails, setCurrentOptionTradeDetails] = useState<OptionTradeDetails | null>(null);
  const [selectedOptionAction, setSelectedOptionAction] = useState<'buyToOpen' | 'sellToOpen' | null>(null);
  
  // Debug logging for selectedOptionAction changes
  useEffect(() => {
    console.log('🎯 selectedOptionAction changed:', selectedOptionAction);
  }, [selectedOptionAction]);

  if (!stock && !mutualFund) {
    return <div>Loading data or symbol not found...</div>;
  }

  const handleAccountSelect = (accountId: string) => {
    setSelectedAccountId(accountId);
    setShowAccountModal(false);
  };


  const handleTradeActionClick = (tradeSymbol: string, action: TradeMode) => {
    if (!symbol) return;
    console.log(`Trade action triggered for ${tradeSymbol}: ${action}`);
    console.log(`Current pageViewMode: ${pageViewMode}`);
    console.log(`Resetting option trade details`);
    setCurrentTradeMode(action);
    setCurrentOptionTradeDetails(null); // Reset option trade details for equity trades
    
    // If we have an account from the URL, use it directly
    if (accountIdFromPath) {
      console.log(`🔍 TradeSymbolPage - Using account from URL:`, accountIdFromPath);
      setSelectedAccountId(accountIdFromPath);
    } else {
      // Otherwise, show account selection modal
      setShowAccountModal(true);
    }
    
    // Update URL to include the trade mode
    const typeParam = pageViewMode === 'stock' ? 'equities' : 'options';
    const modeParam = action ? `&mode=${action}` : '';
    router.push(`/trade/${symbol}?type=${typeParam}${modeParam}`);
  };

  const handleCloseStockDetail = () => {
    router.push('/trade'); // Navigate back to the main trade page
  };

  const handleCloseTradePanel = () => {
    setSelectedAccountId(null);
    setCurrentTradeMode(null);
    setCurrentOptionTradeDetails(null);
  };

  const handleViewModeChange = (mode: 'stock' | 'options') => {
    setPageViewMode(mode);
    // Reset trade state when switching tabs
    setCurrentTradeMode(null);
    setCurrentOptionTradeDetails(null);
    setSelectedAccountId(null);
    // Only reset selectedOptionAction when switching away from options
    if (mode === 'stock') {
      setSelectedOptionAction(null);
    }
    // Update URL to reflect the tab change
    const typeParam = mode === 'stock' ? 'equities' : 'options';
    router.push(`/trade/${symbol}?type=${typeParam}`);
  };

  const handleChangeSymbolClick = () => {
    // Open search modal to select a *different* symbol
    setShowSearchModal(true);
  };

  const handleAddToWatchlist = () => {
    console.log(`${isWatchlisted ? 'Removing from' : 'Adding to'} watchlist...`);
    setIsWatchlisted(!isWatchlisted);
    // TODO: Implement actual API call
  };



  // Handler for clicks within the OptionsChainTable
  const handleOptionTradeClick = (details: OptionTradeDetails) => {
    setCurrentOptionTradeDetails(details);
    setCurrentTradeMode(details.action); // Set trade mode (buy/sell)
    
    // Set the selected option action based on the trade details
    if (details.action === 'buy') {
      setSelectedOptionAction('buyToOpen');
    } else if (details.action === 'sell') {
      setSelectedOptionAction('sellToOpen');
    }
    
    setShowAccountModal(true); // Prompt for account selection
  };

  return (
    <div className="w-full bg-white dark:bg-black">
      <div className="flex flex-col gap-7">
        {/* Main Content Grid: Watchlist | Center (Stock/Options) | Right (Trade Exec) */}
        {/* Changed grid column definition for fixed outer cols, flexible center col */}
        <div className="grid grid-cols-1 lg:grid-cols-[370px_1fr_400px] gap-2">
        
        {/* Column 1: Watchlist */}
        <div className="lg:col-span-1 p-4 rounded-lg border">
          <WatchlistTable 
            showVolumeColumn={false}
            showPriceColumn={false}
          /> 
        </div>

        {/* Column 2: Center Content (Header + Stock Detail or Options Table) */}
        <div className="lg:col-span-1 border space-y-4 p-6 rounded-lg">
          {/* --- Replaced Header with Component START --- */}
          <SecurityHeader 
            symbol={symbol}
            stock={isMutualFundSymbol ? undefined : stock}
            mutualFund={isMutualFundSymbol ? (mutualFund || undefined) : undefined}
            isPositive={isPositive}
            isWatchlisted={isWatchlisted}
            onChangeSymbolClick={handleChangeSymbolClick}
            onAddToWatchlist={handleAddToWatchlist}
            onClose={handleCloseStockDetail}
          />
          {/* --- Replaced Header with Component END --- */}

          {/* --- Tabs for Equities/Options/Mutual Funds --- */}
          {!isMutualFundSymbol && (
            <div className="mt-4">
              <div className="flex border-b border-gray-200 dark:border-gray-700">
                <button
                  onClick={() => handleViewModeChange('stock')}
                  className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors ${
                    pageViewMode === 'stock'
                      ? 'border-blue-500 text-blue-600 dark:text-blue-400'
                      : 'border-transparent text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300'
                  }`}
                >
                  Equities
                </button>
                <button
                  onClick={() => handleViewModeChange('options')}
                  className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors ${
                    pageViewMode === 'options'
                      ? 'border-blue-500 text-blue-600 dark:text-blue-400'
                      : 'border-transparent text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300'
                  }`}
                >
                  Options
                </button>
              </div>
            </div>
          )}

          {/* --- Conditional Content Area --- */}
          <div className="mt-4"> { /* Added top border */}
            {isMutualFundSymbol ? (
         <div className="mt-8">
           <MutualFundDetailPanel 
           symbol={symbol} 
           marketData={mutualFund ? {
             symbol: mutualFund.symbol,
             currentPrice: mutualFund.nav,
             previousClose: mutualFund.marketStats.prevClose,
             dayChange: mutualFund.change,
             dayChangePercent: mutualFund.changePercent,
             volume: 0,
             marketCap: mutualFund.marketStats.totalAssets,
             open: mutualFund.marketStats.open,
             high: mutualFund.marketStats.high,
             low: mutualFund.marketStats.low,
             fiftyTwoWeekHigh: mutualFund.marketStats['52W High'],
             fiftyTwoWeekLow: mutualFund.marketStats['52W Low'],
             sector: 'Mutual Fund',
             description: mutualFund.name,
             fundDetails: mutualFund.fundDetails,
             lastUpdated: new Date().toISOString()
           } : undefined}
           onTradeAction={(tradeSymbol, action) => handleTradeActionClick(tradeSymbol, action)} 
         />
         </div>
            ) : pageViewMode === 'stock' ? (
              <StockDetailPanel 
                symbol={symbol} 
                onTradeAction={(tradeSymbol, action) => handleTradeActionClick(tradeSymbol, action)} 
              />
            ) : (
              <OptionsChainTable 
                symbol={symbol} 
                onOptionTradeClick={handleOptionTradeClick}
                currentOptionTrade={currentOptionTradeDetails}
                selectedAction={selectedOptionAction}
              />
            )}
          </div>
        </div>

        {/* Column 3: Right Content (Trade Execution or Placeholder) */}
        <div className="lg:col-span-1 rounded-md">
          {(() => {
            console.log('🔍 TradeSymbolPage - Rendering check:');
            console.log('  - selectedAccountId:', selectedAccountId);
            console.log('  - currentTradeMode:', currentTradeMode);
            console.log('  - Should show panel:', selectedAccountId && currentTradeMode);
            return null;
          })()}
          {selectedAccountId && currentTradeMode ? (
            <div className="bg-white border p-6 rounded-lg shadow-md">
            <TradeExecutionPanel
              symbol={symbol}
              accountId={selectedAccountId}
              initialTradeMode={currentTradeMode}
              strikePrice={pageViewMode === 'options' ? currentOptionTradeDetails?.strikePrice : undefined}
              optionType={pageViewMode === 'options' ? currentOptionTradeDetails?.optionType : undefined}
              limitPrice={pageViewMode === 'options' ? currentOptionTradeDetails?.price : undefined}
              skipSegmentedControl={pageViewMode === 'options' ? currentOptionTradeDetails?.skipSegmentedControl : undefined}
              selectedOptionAction={selectedOptionAction || undefined}
              onSelectedOptionActionChange={setSelectedOptionAction}
              onClose={handleCloseTradePanel}
            />
            </div>
          ) : (
            <div className="h-full flex items-center justify-center border border-dashed rounded-md p-16">
              <p className="text-sm text-muted-foreground text-center">
                  Select Buy or Sell on the left to choose an account and start trading.
              </p>
            </div>
          )}
        </div>

        </div> { /* End of main 3-column grid */ }
      </div>

      {/* Modals remain outside the main grid */}
      <SearchModal
         isOpen={showSearchModal}
         onOpenChange={setShowSearchModal}
         onSelectSymbol={() => {}}
      />
      {symbol && (
          <AccountSelectionModal
              isOpen={showAccountModal}
              onOpenChange={setShowAccountModal}
              onAccountSelect={handleAccountSelect}
          />
      )}
    </div>
  );
} 