'use client'

import { useState, useMemo } from 'react'
import { useRouter, useParams } from 'next/navigation'
import { 
  StockDetailPanel, 
  STOCK_DATA,
  StockInfo
} from '@/components/trade/StockDetailPanel'
import { useAccountData } from '@/contexts/SupabaseAccountDataContext'
import { TradeExecutionPanel } from '@/components/trade/TradeExecutionPanel'
import { AccountSelectionModal } from '@/components/trade/AccountSelectionModal'
import { SearchModal } from '@/components/trade/SearchModal'
import { WatchlistTable } from '@/components/trade/SearchAndWatchlist'
import { OptionsChainTable } from '@/components/trade/OptionsChainTable'
import { SecurityHeader } from '@/components/trade/SecurityHeader'
import { OptionTradeDetails } from '@/components/trade/OptionsChainTable'

type TradeMode = 'buy' | 'sell' | null

export default function TradeSymbolPage() {
  const router = useRouter();
  const params = useParams();
  const symbol = params?.symbol as string;
  const { data } = useAccountData();
  const marketData = data?.marketData;

  const stock = useMemo(() => {
    const upperSymbol = symbol?.toUpperCase();
    
    console.log('🔍 TradePage - Symbol:', upperSymbol);
    console.log('🔍 TradePage - Market data available:', marketData?.length || 0);
    
    // Try to get real market data first
    const realMarketData = marketData?.find(m => m.symbol === upperSymbol);
    
    console.log('🔍 TradePage - Found real market data for', upperSymbol, ':', realMarketData);
    
    if (realMarketData) {
      console.log('✅ TradePage - Using real market data for', upperSymbol, '- Price:', realMarketData.currentPrice);
      // Create StockInfo from real market data
      const stockInfo: StockInfo = {
        name: realMarketData.description || `${upperSymbol} Inc.`,
        exchangeInfo: 'Nasdaq • USD',
        price: realMarketData.currentPrice || 0,
        change: realMarketData.dayChange || 0,
        changePercent: realMarketData.dayChangePercent || 0,
        peRatio: 30.5, // Mock PE ratio
        volume: realMarketData.volume || 0,
        chartData: {}, // Will be generated by StockDetailPanel
        marketStats: {
          open: realMarketData.open || 0,
          high: realMarketData.high || 0,
          low: realMarketData.low || 0,
          prevClose: realMarketData.previousClose || 0,
          '52W High': realMarketData.fiftyTwoWeekHigh || 0,
          '52W Low': realMarketData.fiftyTwoWeekLow || 0
        }
      };
      console.log('📊 TradePage - Created stockInfo:', stockInfo);
      return stockInfo;
    } else {
      console.log('❌ TradePage - No real market data found, using mock data for', upperSymbol);
      // Fallback to mock data if not found
      const mockData = STOCK_DATA[upperSymbol] || STOCK_DATA.AAPL;
      console.log('📊 TradePage - Using mock data:', mockData);
      return mockData;
    }
  }, [symbol, marketData]);
  
  const isPositive = stock ? stock.change >= 0 : false;

  const [selectedAccountId, setSelectedAccountId] = useState<string | null>(null);
  const [showAccountModal, setShowAccountModal] = useState(false);
  const [showSearchModal, setShowSearchModal] = useState(false);
  const [currentTradeMode, setCurrentTradeMode] = useState<TradeMode>(null);
  const [pageViewMode, setPageViewMode] = useState<'stock' | 'options'>('stock');
  const [isWatchlisted, setIsWatchlisted] = useState(false);
  const [currentOptionTradeDetails, setCurrentOptionTradeDetails] = useState<OptionTradeDetails | null>(null);

  if (!stock) {
    return <div>Loading stock data or symbol not found...</div>;
  }

  const handleAccountSelect = (accountId: string) => {
    setSelectedAccountId(accountId);
    setShowAccountModal(false);
  };

  const handleTradeActionClick = (tradeSymbol: string, action: TradeMode) => {
    if (!symbol) return;
    console.log(`Trade action triggered for ${tradeSymbol}: ${action}`);
    console.log(`Current pageViewMode: ${pageViewMode}`);
    console.log(`Resetting option trade details`);
    setCurrentTradeMode(action);
    setCurrentOptionTradeDetails(null); // Reset option trade details for equity trades
    setShowAccountModal(true);
  };

  const handleCloseStockDetail = () => {
    router.push('/trade'); // Navigate back to the main trade page
  };

  const handleCloseTradePanel = () => {
    setSelectedAccountId(null);
    setCurrentTradeMode(null);
    setCurrentOptionTradeDetails(null);
  };

  const handleViewModeChange = (mode: 'stock' | 'options') => {
    setPageViewMode(mode);
    // Reset trade state when switching tabs
    setCurrentTradeMode(null);
    setCurrentOptionTradeDetails(null);
    setSelectedAccountId(null);
  };

  const handleChangeSymbolClick = () => {
    // Open search modal to select a *different* symbol
    setShowSearchModal(true);
  };

  const handleAddToWatchlist = () => {
    console.log(`${isWatchlisted ? 'Removing from' : 'Adding to'} watchlist...`);
    setIsWatchlisted(!isWatchlisted);
    // TODO: Implement actual API call
  };

  const handleSymbolSelectFromModal = (newSymbol: string) => {
    // Navigate to the new symbol's page
    setSelectedAccountId(null);
    setCurrentTradeMode(null);
    setShowSearchModal(false);
    router.push(`/trade/${newSymbol}`);
  };

  const handleSymbolSelectFromWatchlist = (newSymbol: string) => {
    // Similar to selecting from modal, navigate to the new symbol's page
    // Reset state specific to the *current* symbol trade
    setSelectedAccountId(null);
    setCurrentTradeMode(null);
    // Don't close search modal as it wasn't open
    router.push(`/trade/${newSymbol}`);
  };



  // Handler for clicks within the OptionsChainTable
  const handleOptionTradeClick = (details: OptionTradeDetails) => {
    console.log("🚀 Option trade initiated:", details);
    console.log("🔍 Current pageViewMode:", pageViewMode);
    setCurrentOptionTradeDetails(details);
    setCurrentTradeMode(details.action); // Set trade mode (buy/sell)
    setShowAccountModal(true); // Prompt for account selection
  };



  return (
    <div>
  

      {/* Main Content Grid: Watchlist | Center (Stock/Options) | Right (Trade Exec) */}
      {/* Changed grid column definition for fixed outer cols, flexible center col */}
      <div className="grid grid-cols-1 lg:grid-cols-[370px_1fr_400px] gap-2">
        
        {/* Column 1: Watchlist */}
        <div className="lg:col-span-1 p-4 rounded-lg border">
          <WatchlistTable 
            onSelectSymbol={handleSymbolSelectFromWatchlist} 
            showVolumeColumn={false}
            showPriceColumn={false}
          /> 
        </div>

        {/* Column 2: Center Content (Header + Stock Detail or Options Table) */}
        <div className="lg:col-span-1 border space-y-4 p-6 rounded-lg">
          {/* --- Replaced Header with Component START --- */}
          <SecurityHeader 
            symbol={symbol}
            stock={stock}
            isPositive={isPositive}
            isWatchlisted={isWatchlisted}
            onChangeSymbolClick={handleChangeSymbolClick}
            onAddToWatchlist={handleAddToWatchlist}
            onClose={handleCloseStockDetail}
          />
          {/* --- Replaced Header with Component END --- */}

          {/* --- Tabs for Equities/Options --- */}
          <div className="mt-4">
            <div className="flex border-b border-gray-200 dark:border-gray-700">
              <button
                onClick={() => handleViewModeChange('stock')}
                className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors ${
                  pageViewMode === 'stock'
                    ? 'border-blue-500 text-blue-600 dark:text-blue-400'
                    : 'border-transparent text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300'
                }`}
              >
                Equities
              </button>
              <button
                onClick={() => handleViewModeChange('options')}
                className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors ${
                  pageViewMode === 'options'
                    ? 'border-blue-500 text-blue-600 dark:text-blue-400'
                    : 'border-transparent text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300'
                }`}
              >
                Options
              </button>
            </div>
          </div>

          {/* --- Conditional Content Area --- */}
          <div className="mt-4"> { /* Added top border */}
            {pageViewMode === 'stock' ? (
              <StockDetailPanel 
                symbol={symbol} 
                onTradeAction={(tradeSymbol, action) => handleTradeActionClick(tradeSymbol, action)} 
              />
            ) : (
              <OptionsChainTable 
                symbol={symbol} 
                onOptionTradeClick={handleOptionTradeClick}
                currentOptionTrade={currentOptionTradeDetails}
              />
            )}
          </div>
        </div>

        {/* Column 3: Right Content (Trade Execution or Placeholder) */}
        <div className="lg:col-span-1 rounded-md">
          {selectedAccountId && currentTradeMode ? (
            <div className="bg-white border p-6 rounded-lg shadow-md">
            <TradeExecutionPanel
              symbol={symbol}
              accountId={selectedAccountId}
              initialTradeMode={currentTradeMode}
              strikePrice={pageViewMode === 'options' ? currentOptionTradeDetails?.strikePrice : undefined}
              optionType={pageViewMode === 'options' ? currentOptionTradeDetails?.optionType : undefined}
              limitPrice={pageViewMode === 'options' ? currentOptionTradeDetails?.price : undefined}
              skipSegmentedControl={pageViewMode === 'options' ? currentOptionTradeDetails?.skipSegmentedControl : undefined}
              onClose={handleCloseTradePanel}
            />
            </div>
          ) : (
            <div className="h-full flex items-center justify-center border border-dashed rounded-md p-16">
              <p className="text-sm text-muted-foreground text-center">
                  Select Buy or Sell on the left to choose an account and start trading.
              </p>
            </div>
          )}
        </div>

      </div> { /* End of main 3-column grid */ }

      {/* Modals remain outside the main grid */}
      <SearchModal
         isOpen={showSearchModal}
         onOpenChange={setShowSearchModal}
         onSelectSymbol={handleSymbolSelectFromModal}
      />
      {symbol && (
          <AccountSelectionModal
              isOpen={showAccountModal}
              onOpenChange={setShowAccountModal}
              onAccountSelect={handleAccountSelect}
          />
      )}
    </div>
  );
} 