'use client'

import { useParams, useRouter } from 'next/navigation' 
import { useState, useMemo } from 'react'
import { Plus } from 'lucide-react'
import { SearchModal } from '@/components/trade/SearchModal' 
import { StockDetailPanel, STOCK_DATA, StockInfo } from '@/components/trade/StockDetailPanel'
import { useAccountData } from '@/contexts/SupabaseAccountDataContext'
import { TradeExecutionPanel } from '@/components/trade/TradeExecutionPanel'
import { OptionsChainTable } from '@/components/trade/OptionsChainTable'
import { SecurityHeader } from '@/components/trade/SecurityHeader'
import { OptionTradeDetails } from '@/components/trade/OptionsChainTable'

type TradeMode = 'buy' | 'sell' | null
type PageViewMode = 'stock' | 'options'

export default function AccountSymbolTradePage() {
  const params = useParams();
  const router = useRouter();
  const accountId = params?.accountId as string;
  const symbol = params?.symbol as string;
  const { data } = useAccountData();
  const marketData = data?.marketData;

  const stock = useMemo(() => {
    const upperSymbol = symbol?.toUpperCase();
    
    // Try to get real market data first
    const realMarketData = marketData?.find(m => m.symbol === upperSymbol);
    
    if (realMarketData) {
      // Create StockInfo from real market data
      const stockInfo: StockInfo = {
        name: realMarketData.description || `${upperSymbol} Inc.`,
        exchangeInfo: 'Nasdaq • USD',
        price: realMarketData.currentPrice || 0,
        change: realMarketData.dayChange || 0,
        changePercent: realMarketData.dayChangePercent || 0,
        peRatio: 30.5, // Mock PE ratio
        volume: realMarketData.volume || 0,
        chartData: {}, // Will be generated by StockDetailPanel
        marketStats: {
          open: realMarketData.open || 0,
          high: realMarketData.high || 0,
          low: realMarketData.low || 0,
          prevClose: realMarketData.previousClose || 0,
          '52W High': realMarketData.fiftyTwoWeekHigh || 0,
          '52W Low': realMarketData.fiftyTwoWeekLow || 0
        }
      };
      return stockInfo;
    } else {
      // Fallback to mock data if not found
      return STOCK_DATA[upperSymbol] || STOCK_DATA.AAPL;
    }
  }, [symbol, marketData]);

  const isPositive = stock ? stock.change >= 0 : false;

  const [showSearchModal, setShowSearchModal] = useState(false)
  const [tradeMode, setTradeMode] = useState<TradeMode>(null);
  const [pageViewMode, setPageViewMode] = useState<PageViewMode>('stock');
  const [isWatchlisted, setIsWatchlisted] = useState(false);
  const [currentOptionTradeDetails, setCurrentOptionTradeDetails] = useState<OptionTradeDetails | null>(null);

  if (!stock) {
    return <div>Loading stock data or symbol not found...</div>; 
  }

  const handleSymbolChange = (newSymbol: string) => {
     router.push(`/account/${accountId}/trade/${newSymbol}`);
     setShowSearchModal(false);
     setTradeMode(null);
  }

  const handleAccountTradeAction = (tradeSymbol: string, action: TradeMode) => {
      console.log(`Trade action triggered for ${tradeSymbol}: ${action}`);
      // Ensure we are not carrying over option selection when doing equity trades
      setCurrentOptionTradeDetails(null);
      setTradeMode(action);
  }

  const handleOptionTradeClick = (details: OptionTradeDetails) => {
    console.log("Option trade initiated:", details);
    setCurrentOptionTradeDetails(details);
    setTradeMode(details.action);
  };



  const handleAddToWatchlist = () => {
    console.log(`${isWatchlisted ? 'Removing from' : 'Adding to'} watchlist...`);
    setIsWatchlisted(!isWatchlisted);
  };

  const pageOnChangeSymbolClick = () => setShowSearchModal(true);

  const handleCloseMainPanel = () => {
    router.push(`/account/${accountId}/trade`);
  };
  
  const handleCloseTradePanel = () => {
    setTradeMode(null);
    setCurrentOptionTradeDetails(null);
  };

  return (
    <div className="flex flex-col sm:flex-row gap-8  rounded-md">
      <div className=" relative flex-grow rounded-md">
        <SecurityHeader 
            symbol={symbol}
            stock={stock}
            isPositive={isPositive}
            isWatchlisted={isWatchlisted}
          onChangeSymbolClick={pageOnChangeSymbolClick}
          onAddToWatchlist={handleAddToWatchlist}
          onClose={handleCloseMainPanel}
          isDrawer={false}
        />

        {/* Tabs */}
        <div className="flex space-x-8 border-b mt-4 mb-2">
          <button
            onClick={() => {
              setPageViewMode('stock');
              // Clear option selection when switching back to equities
              setCurrentOptionTradeDetails(null);
              // Hide the trade panel until user clicks Buy/Sell again
              setTradeMode(null);
            }}
            className={`pb-2 font-medium transition-colors ${
              pageViewMode === 'stock'
                ? 'border-b-2 border-primary text-primary'
                : 'text-muted-foreground hover:text-foreground'
            }`}
          >
            Equities
          </button>
          <button
            onClick={() => {
              // Switching to Options should not auto-open a trade panel
              setPageViewMode('options');
              setTradeMode(null);
              setCurrentOptionTradeDetails(null);
            }}
            className={`pb-2 font-medium transition-colors ${
              pageViewMode === 'options'
                ? 'border-b-2 border-primary text-primary'
                : 'text-muted-foreground hover:text-foreground'
            }`}
          >
            Options
          </button>
        </div>


        <div className="">
          {pageViewMode === 'stock' ? (
            <StockDetailPanel 
                symbol={symbol} 
                onTradeAction={handleAccountTradeAction} 
            />
          ) : (
            <OptionsChainTable 
               symbol={symbol} 
               onOptionTradeClick={handleOptionTradeClick}
               currentOptionTrade={currentOptionTradeDetails}
            />
          )}
        </div>
      </div>

      <div className="sm:w-[400px] h-full flex-shrink-0">
        <div className="space-y-6"> 
          {tradeMode ? (
            <div className="bg-white border bg-card-blend dark:bg-card-blend-dark p-6 rounded-lg shadow-md">
              <TradeExecutionPanel 
                  symbol={symbol} 
                  accountId={accountId} 
                  initialTradeMode={tradeMode} 
                  strikePrice={pageViewMode === 'options' ? currentOptionTradeDetails?.strikePrice : undefined}
                  optionType={pageViewMode === 'options' ? currentOptionTradeDetails?.optionType : undefined}
                  limitPrice={pageViewMode === 'options' ? currentOptionTradeDetails?.price : undefined}
                  isOptionTradeOverride={pageViewMode === 'options'}
                  skipSegmentedControl={pageViewMode === 'options' ? currentOptionTradeDetails?.skipSegmentedControl : false}
                  onClose={handleCloseTradePanel}
              />
            </div>
          ) : (
              <div className="h-full flex items-center justify-center p-6 border border-dashed border-gray-400 dark:border-gray-700 rounded-lg  min-h-[500px]">
                  <div className="text-center">
                <Plus className="h-8 w-8 text-muted-foreground mx-auto mb-2" />
                <p className="text-sm text-muted-foreground">Select Buy or Sell to start trading</p>
              </div>
            </div>
          )}
        </div>
      </div>

      <SearchModal 
        isOpen={showSearchModal}
        onOpenChange={setShowSearchModal}
        onSelectSymbol={handleSymbolChange}
      />
    </div>
  );
} 