'use client'

import { useState, useMemo } from 'react'
// import dynamic from 'next/dynamic'; // Remove dynamic import
import { HoldingsTable } from './HoldingsTable'
import { Card } from '@/components/ui/card'
import { SearchModal } from '@/components/trade/SearchModal'
import { StockDetailPanel } from '@/components/trade/StockDetailPanel'
import { TradeExecutionPanel } from '@/components/trade/TradeExecutionPanel'
// Re-import DonutChart
import { DonutChart } from '@/components/charts/DonutChart'; 
import { Info, X, FileText, History } from 'lucide-react' // Added FileText, History
// import { AccountSelectionModal } from '@/components/trade/AccountSelectionModal' // Removed unused import
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import { 
  Drawer, 
  DrawerContent, 
  DrawerHeader,
  DrawerTitle,
  DrawerClose
} from "@/components/ui/drawer"
import { Button } from "@/components/ui/button"
import { OptionTradeDetails } from '@/components/trade/OptionsChainTable'
// import { OptionsChainTable } from '@/components/trade/OptionsChainTable' // Removed unused import
import { STOCK_DATA } from '@/components/trade/StockDetailPanel' // Keep STOCK_DATA if needed
import { SecurityHeader } from '@/components/trade/SecurityHeader'
import { useAccountData } from '@/contexts/SupabaseAccountDataContext'
import { LastUpdated } from '@/components/ui/last-updated'


type TradeMode = 'buy' | 'sell' | null
type DrawerOptionTradeDetails = Omit<OptionTradeDetails, 'symbol'>;

interface AccountClientContentProps {
  accountId: string;
}

export function AccountClientContent({ accountId }: AccountClientContentProps) {
  const accountIdFromParams = accountId;
  const { data: accountData, loading, error, getHoldingsWithDetails } = useAccountData();

  const [isSearchModalOpen, setIsSearchModalOpen] = useState(false);
  const [isStockDrawerOpen, setIsStockDrawerOpen] = useState(false);
  const [selectedSymbolInDrawer, setSelectedSymbolInDrawer] = useState<string | null>(null);
  const [drawerTradeMode, setDrawerTradeMode] = useState<TradeMode>(null);
  const [drawerOptionTradeDetails, setDrawerOptionTradeDetails] = useState<DrawerOptionTradeDetails | null>(null);
  const [isDrawerWatchlisted, setIsDrawerWatchlisted] = useState(false);

  const drawerStockData = useMemo(() => {
    if (!selectedSymbolInDrawer) return null;
    
    // Try to get real market data first
    const realMarketData = accountData?.marketData?.find(m => m.symbol === selectedSymbolInDrawer.toUpperCase());
    
    if (realMarketData) {
      // Create StockInfo from real market data
      const stockInfo = {
        name: realMarketData.description || `${selectedSymbolInDrawer.toUpperCase()} Inc.`,
        exchangeInfo: 'Nasdaq • USD',
        price: realMarketData.currentPrice || 0,
        change: realMarketData.dayChange || 0,
        changePercent: realMarketData.dayChangePercent || 0,
        peRatio: 30.5, // Mock PE ratio
        volume: realMarketData.volume || 0,
        chartData: {}, // Will be generated by StockDetailPanel
        marketStats: {
          open: realMarketData.open || 0,
          high: realMarketData.high || 0,
          low: realMarketData.low || 0,
          prevClose: realMarketData.previousClose || 0,
          '52W High': realMarketData.fiftyTwoWeekHigh || 0,
          '52W Low': realMarketData.fiftyTwoWeekLow || 0
        }
      };
      return stockInfo;
    } else {
      // Fallback to mock data if not found
      return STOCK_DATA[selectedSymbolInDrawer.toUpperCase()] || null;
    }
  }, [selectedSymbolInDrawer, accountData?.marketData]);

  const isDrawerPositive = useMemo(() => 
     drawerStockData ? drawerStockData.change >= 0 : false
  , [drawerStockData]);

  const handleHoldingClick = (symbol: string) => {
    setSelectedSymbolInDrawer(symbol);
    setIsStockDrawerOpen(true);
    setDrawerTradeMode(null);
    setDrawerOptionTradeDetails(null);
  };

  const handleSymbolSelectFromSearch = () => {
    setIsSearchModalOpen(false);
  };

  const handleTradeActionFromDrawer = (tradeSymbol: string, action: TradeMode) => {
    setDrawerTradeMode(action);
    setDrawerOptionTradeDetails(null);
  };

  const handleCloseDrawerTradePanel = () => {
    setDrawerTradeMode(null);
    setDrawerOptionTradeDetails(null);
  };

  const handleAddToWatchlistFromDrawer = () => {
    if (!selectedSymbolInDrawer) return;
    setIsDrawerWatchlisted(!isDrawerWatchlisted);
    // TODO: Implement actual API call
  };

  // Helper function to get sector colors
  const getSectorColor = (sector: string) => {
    const colors = {
      'Technology': '#A16207',
      'Financial Services': '#881337',
      'Consumer Discretionary': '#D97706',
      'Automotive': '#57534E',
      'Healthcare': '#7C2D12',
      'Energy': '#1E40AF',
      'Utilities': '#059669',
      'Real Estate': '#7C3AED'
    };
    return colors[sector as keyof typeof colors] || '#6B7280';
  };

  // Calculate dynamic data from accountData
  const portfolioData = useMemo(() => {
    if (!accountData || !accountData.balances) {
      return null;
    }

    // Get holdings with full details first
    const holdingsWithDetails = getHoldingsWithDetails();
    
    // Calculate total market value from holdings
    const totalMarketValue = holdingsWithDetails.reduce((sum, holding) => sum + (holding.marketValue || 0), 0);
    const totalInvestedValue = holdingsWithDetails.reduce((sum, holding) => sum + (holding.quantity * holding.avgPrice), 0);
    
    // Use calculated values or fall back to account data
    const totalValue = totalMarketValue + (accountData.balances.cash || 0);
    const investedValue = totalInvestedValue;
    
    // Calculate unrealized G/L from holdings
    const unrealizedGL = holdingsWithDetails.reduce((sum, holding) => sum + (holding.unrealizedGL || 0), 0);
    const unrealizedGLPercent = investedValue > 0 ? (unrealizedGL / investedValue) * 100 : 0;
    

    // Calculate asset allocation from holdings
    const assetAllocation = holdingsWithDetails.reduce((acc, holding) => {
      const marketValue = holding.marketValue || 0;
      const existing = acc.find(item => item.name === holding.security.sector);
      if (existing) {
        existing.value += marketValue;
      } else {
        acc.push({
          name: holding.security.sector,
          value: marketValue,
          color: getSectorColor(holding.security.sector)
        });
      }
      return acc;
    }, [] as Array<{ name: string; value: number; color: string }>);

    // Ensure we have valid numbers
    const safeUnrealizedGL = isNaN(unrealizedGL) ? 0 : unrealizedGL;
    const safeUnrealizedGLPercent = isNaN(unrealizedGLPercent) ? 0 : unrealizedGLPercent;
    const safeTotalValue = isNaN(totalValue) ? 0 : totalValue;
    

    return {
      portfolioValue: `$${safeTotalValue.toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      todaysGL: { 
        amount: `${safeUnrealizedGL >= 0 ? '+' : ''}$${safeUnrealizedGL.toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 
        percentage: `${safeUnrealizedGLPercent.toFixed(2)}%` 
      },
      totalGL: { 
        amount: `${safeUnrealizedGL >= 0 ? '+' : ''}$${safeUnrealizedGL.toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 
        percentage: `${safeUnrealizedGLPercent.toFixed(2)}%` 
      },
      positions: { 
        long: { amount: `$${safeTotalValue.toLocaleString('en-US', { minimumFractionDigits: 2 })}` }, 
        short: { amount: '$0.00' } 
      },
      availableCash: `$${(accountData.balances.cash || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      fdicSweep: '$250,000.00',
      marginBalance: `$${(accountData.balances.margin || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      fundsAvailable: `$${(accountData.balances.buyingPower || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      totalAccountValue: `$${safeTotalValue.toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      assetAllocation: assetAllocation.map(item => ({
        ...item,
        value: safeTotalValue > 0 ? Math.round((item.value / safeTotalValue) * 100) : 0
      }))
    };
  }, [accountData, getHoldingsWithDetails]);

  if (loading) {
    return <div className="min-h-screen flex items-center justify-center">Loading...</div>;
  }

  if (error || !accountData) {
    return <div className="min-h-screen flex items-center justify-center text-red-500">Error loading account data</div>;
  }

  return (
    <div className="min-h-screen rounded-md space-y-4 md:space-y-4 ">
         {/* Holdings Title and Action Buttons */}
         <div className="w-full flex justify-between items-center mb-8">
            <h2 className="text-3xl font-serif ">Holdings</h2>
            <div className="flex items-center space-x-2">
              <Button variant="secondary" size="sm">
                <FileText className="mr-2 h-4 w-4" />
                Export
              </Button>
              <Button variant="secondary" size="sm">
                <History className="mr-2 h-4 w-4" />
                View History
              </Button>
            </div>
          </div>
      <div className="w-full flex flex-col md:grid md:grid-cols-3 gap-4 md:gap-4">
     
        <Card className="md:col-span-2 min-w-0  p-4 md:p-6 flex flex-col justify-between bg-accent">
          <div className="flex-grow space-y-4">
            <div>
              <h3>Portfolio Market Value</h3>
              <span className="text-3xl font-serif font-medium text-black dark:text-white break-words">{portfolioData?.portfolioValue}</span>
            </div>

            {/* Combined Grid for all data points - Make Responsive */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-4 text-sm"> 
              {/* Today's G/L */}
              <div>
                <span className="text-xs text-muted-foreground block">Today&apos;s G/L</span>
                <span className="text-positive font-medium">
                  {portfolioData?.todaysGL.amount} ({portfolioData?.todaysGL.percentage})
                </span>
              </div>
              {/* Total G/L */}
              <div>
                <span className="text-xs text-muted-foreground block">Total G/L</span>
                <span className="text-positive font-medium">
                  {portfolioData?.totalGL.amount} ({portfolioData?.totalGL.percentage})
                </span>
              </div>
              {/* Available Cash (Moved Here) */}
              <div>
                <span className="text-xs text-muted-foreground block">Available Cash</span>
                <span className="text-md dark:text-white font-medium break-words">{portfolioData?.availableCash}</span>
              </div>
              {/* Long (Moved from 2nd row) */}
              <div>
                <span className="text-xs text-muted-foreground block">Long</span>
                <span className="text-black dark:text-white font-medium">{portfolioData?.positions.long.amount}</span>
              </div>
              {/* Short (Moved from 1st row) */}
              <div>
                <span className="text-xs text-muted-foreground block">Short</span>
                <span className="text-negative font-medium">{portfolioData?.positions.short.amount}</span>
              </div>
              {/* Funds Available */}
              <div>
                <div className="flex items-center gap-1">
                  <span className="text-xs text-muted-foreground">Funds available</span>
                  <TooltipProvider>
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <button className="p-0.5 rounded-full hover:bg-black/10 dark:hover:bg-white/10 transition shrink-0">
                          <Info className="w-3 h-3 text-muted-foreground" />
                        </button>
                      </TooltipTrigger>
                      <TooltipContent>
                        <p>Funds available for withdrawal or trading.</p>
                      </TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                </div>
                <span className="text-md dark:text-white font-medium break-words">{portfolioData?.fundsAvailable}</span>
              </div>
              {/* Margin Balance */}
              <div>
                <span className="text-xs text-muted-foreground block">Margin Balance</span>
                <span className="text-md dark:text-white font-medium break-words">{portfolioData?.marginBalance}</span>
              </div>
              {/* Total Account Value */}
              <div>
                 <div className="flex items-center gap-1">
                  <span className="text-xs text-muted-foreground">Total account value</span>
                  <TooltipProvider>
                    <Tooltip>
                      <TooltipTrigger asChild>
                         <button className="p-0.5 rounded-full hover:bg-black/10 dark:hover:bg-white/10 transition shrink-0">
                           <Info className="w-3 h-3 text-muted-foreground" />
                         </button>
                      </TooltipTrigger>
                      <TooltipContent>
                         <p>Total value includes cash, investments, and other assets in your account</p>
                      </TooltipContent>
                    </Tooltip>
                   </TooltipProvider>
                 </div>
                <span className="text-md dark:text-white font-medium break-words">{portfolioData?.totalAccountValue}</span>
              </div>
              {/* FDIC Sweep */}
              <div>
                <span className="text-xs text-muted-foreground block">FDIC Sweep</span>
                <span className="text-md dark:text-white font-medium break-words">{portfolioData?.fdicSweep}</span>
              </div>
            </div>
          </div>
          <LastUpdated 
            timestamp="Updated 01/08/2025 8:05 AM ET" 
            className="mt-4 md:mt-6 pt-3"
          />
        </Card>

        <Card className="min-w-0  md:p-6 flex flex-col justify-between  bg-accent">
          <div>
            <div className="flex items-center justify-between mb-4">
              <h3>Asset Allocation</h3>
              <button className="text-sm text-primary hover:underline whitespace-nowrap">Expand view</button>
            </div>
            {/* Use flex-row to place chart and legend side-by-side */}
            <div className='flex flex-row items-center gap-2'> 
                {/* Chart container - reduced gap and increased max width */}
                <div className="flex-shrink-0 w-full max-w-[120px] sm:max-w-[200px]">
                   <DonutChart 
                     data={portfolioData?.assetAllocation || []} 
                     portfolioValue={portfolioData ? parseFloat(portfolioData.portfolioValue.replace(/[$,]/g, '')) : 0}
                   />
                </div>
                {/* Legend container - use flex-col for vertical stacking, items will align left by default */}
                <div className="flex flex-col gap-y-2 text-sm flex-1 min-w-0">
                  {(portfolioData?.assetAllocation || []).map(item => (
                     <div key={item.name} className="flex items-center gap-1.5">
                       <span className="w-2.5 h-2.5 rounded-full flex-shrink-0" style={{ backgroundColor: item.color }}></span>
                       <span className="truncate">{item.name}</span>
                     </div>
                  ))}
                </div>
            </div>
          </div>
          <LastUpdated 
            timestamp="Updated 01/08/2025 8:05 AM ET" 
            className="pt-3"
          />
        </Card>
      </div>
      
       <HoldingsTable 
         onStockClick={handleHoldingClick} 
         holdingsWithDetails={getHoldingsWithDetails()} 
         accountId={accountIdFromParams}
       />
       

      <Drawer direction="right" open={isStockDrawerOpen} onOpenChange={setIsStockDrawerOpen}>
        <DrawerContent className="h-full w-full max-w-2xl flex flex-col bg-white dark:bg-black/50 dark:backdrop-blur-lg">
          <DrawerHeader className="p-4 border-b flex items-center">
            <DrawerTitle className="text-lg font-semibold">
               {/* Intentionally empty title */}
            </DrawerTitle>
            <DrawerClose asChild className="ml-auto">
              <Button variant="secondary" className="flex items-center gap-1">
                <span>Close</span>
                <X className="h-6 w-6" />
              </Button>
            </DrawerClose>
          </DrawerHeader>
          <div className="flex-grow overflow-y-auto h-full p-4">
            {selectedSymbolInDrawer && drawerStockData && (
              drawerTradeMode ? (
                <TradeExecutionPanel
                  symbol={selectedSymbolInDrawer}
                  accountId={accountIdFromParams}
                  initialTradeMode={drawerTradeMode}
                  strikePrice={drawerOptionTradeDetails?.strikePrice}
                  optionType={drawerOptionTradeDetails?.optionType}
                  limitPrice={drawerOptionTradeDetails?.price}
                  onClose={handleCloseDrawerTradePanel}
                />
              ) : (
                 <> 
                   <SecurityHeader 
                     symbol={selectedSymbolInDrawer}
                      stock={drawerStockData}
                      isPositive={isDrawerPositive}
                      isWatchlisted={isDrawerWatchlisted}
                     onChangeSymbolClick={() => setIsSearchModalOpen(true)}
                     onAddToWatchlist={handleAddToWatchlistFromDrawer}
                     isDrawer={true}
                   />
                   <div className="mt-4 pt-4 border-t">
                     <StockDetailPanel 
                       symbol={selectedSymbolInDrawer} 
                       onTradeAction={handleTradeActionFromDrawer}
                     />
                   </div>
                 </>
              )
            )}
            {selectedSymbolInDrawer && !drawerStockData && (
                <div className="p-4 text-center text-muted-foreground">
                    Could not load data for symbol: {selectedSymbolInDrawer}
                </div>
            )}
          </div>
        </DrawerContent>
      </Drawer>

      <SearchModal 
        isOpen={isSearchModalOpen} 
        onOpenChange={setIsSearchModalOpen}
        onSelectSymbol={handleSymbolSelectFromSearch}
      />
    </div>
  );
}