'use client'

import { useState, useMemo } from 'react'
// import dynamic from 'next/dynamic'; // Remove dynamic import
import { HoldingsTable } from './HoldingsTable'
import { Card } from '@/components/ui/card'
import { SearchModal } from '@/components/trade/SearchModal'
import { StockDetailPanel } from '@/components/trade/StockDetailPanel'
import { TradeExecutionPanel } from '@/components/trade/TradeExecutionPanel'
// Re-import DonutChart
import { DonutChart } from '@/components/charts/DonutChart'; 
import { Info, X, FileText, History, RefreshCw } from 'lucide-react' // Added FileText, History, RefreshCw
// import { AccountSelectionModal } from '@/components/trade/AccountSelectionModal' // Removed unused import
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import { 
  Drawer, 
  DrawerContent, 
  DrawerHeader,
  DrawerTitle,
  DrawerClose
} from "@/components/ui/drawer"
import { Button } from "@/components/ui/button"
import { OptionTradeDetails } from '@/components/trade/OptionsChainTable'
// import { OptionsChainTable } from '@/components/trade/OptionsChainTable' // Removed unused import
import { STOCK_DATA } from '@/components/trade/StockDetailPanel' // Keep STOCK_DATA if needed
import { SecurityHeader } from '@/components/trade/SecurityHeader'
import { useAccountData } from '@/contexts/AccountDataContext'
import { getChartColorByIndex } from '@/lib/chartColors'
import { PageHeading } from '@/components/layout/PageHeading'


type TradeMode = 'buy' | 'sell' | null
type DrawerOptionTradeDetails = Omit<OptionTradeDetails, 'symbol'>;

interface AccountContentProps {
  accountId: string;
}

export function AccountContent({ accountId }: AccountContentProps) {
  const accountIdFromParams = accountId;
  const { data: accountData, loading, error, getHoldingsWithDetails } = useAccountData();

  const [isSearchModalOpen, setIsSearchModalOpen] = useState(false);
  const [isStockDrawerOpen, setIsStockDrawerOpen] = useState(false);
  const [selectedSymbolInDrawer, setSelectedSymbolInDrawer] = useState<string | null>(null);
  const [drawerTradeMode, setDrawerTradeMode] = useState<TradeMode>(null);
  const [drawerOptionTradeDetails, setDrawerOptionTradeDetails] = useState<DrawerOptionTradeDetails | null>(null);
  const [isDrawerWatchlisted, setIsDrawerWatchlisted] = useState(false);

  const drawerStockData = useMemo(() => {
    if (!selectedSymbolInDrawer) return null;
    
    // Try to get real market data first
    const realMarketData = accountData?.marketData?.find(m => m.symbol === selectedSymbolInDrawer.toUpperCase());
    
    if (realMarketData) {
      // Create StockInfo from real market data
      const stockInfo = {
        name: realMarketData.description || `${selectedSymbolInDrawer.toUpperCase()} Inc.`,
        exchangeInfo: 'Nasdaq • USD',
        price: realMarketData.currentPrice || 0,
        change: realMarketData.dayChange || 0,
        changePercent: realMarketData.dayChangePercent || 0,
        peRatio: 30.5, // Mock PE ratio
        volume: realMarketData.volume || 0,
        chartData: {}, // Will be generated by StockDetailPanel
        marketStats: {
          open: realMarketData.open || 0,
          high: realMarketData.high || 0,
          low: realMarketData.low || 0,
          prevClose: realMarketData.previousClose || 0,
          '52W High': realMarketData.fiftyTwoWeekHigh || 0,
          '52W Low': realMarketData.fiftyTwoWeekLow || 0
        }
      };
      return stockInfo;
    } else {
      // Fallback to mock data if not found
      return STOCK_DATA[selectedSymbolInDrawer.toUpperCase()] || null;
    }
  }, [selectedSymbolInDrawer, accountData?.marketData]);

  const isDrawerPositive = useMemo(() => 
     drawerStockData ? drawerStockData.change >= 0 : false
  , [drawerStockData]);

  const handleHoldingClick = (symbol: string) => {
    setSelectedSymbolInDrawer(symbol);
    setIsStockDrawerOpen(true);
    setDrawerTradeMode(null);
    setDrawerOptionTradeDetails(null);
  };

  const handleSymbolSelectFromSearch = () => {
    setIsSearchModalOpen(false);
  };

  const handleTradeActionFromDrawer = (tradeSymbol: string, action: TradeMode) => {
    setDrawerTradeMode(action);
    setDrawerOptionTradeDetails(null);
  };

  const handleCloseDrawerTradePanel = () => {
    setDrawerTradeMode(null);
    setDrawerOptionTradeDetails(null);
  };

  const handleAddToWatchlistFromDrawer = () => {
    if (!selectedSymbolInDrawer) return;
    setIsDrawerWatchlisted(!isDrawerWatchlisted);
    // TODO: Implement actual API call
  };

  // Helper function to get asset type colors using chart color system
  const getAssetTypeColor = (assetType: string) => {
    // Map asset types to chart color indices (cycling through 1-6)
    const assetTypeMap: Record<string, number> = {
      'Equities': 1,
      'Mutual Funds': 2,
      'Options': 3,
      'Fixed Income': 4,
      'Cash': 5,
      'Annuities': 6,
      'Others': 1
    };
    
    const colorIndex = assetTypeMap[assetType] || 1;
    return getChartColorByIndex(colorIndex);
  };

  // Helper function to determine asset type from holding
  const getAssetType = (holding: ReturnType<typeof getHoldingsWithDetails>[0]): string => {
    const symbol = holding.symbol?.toUpperCase() || '';
    const description = (holding.security?.description || '').toLowerCase();
    const securityType = (holding.security as { type?: string })?.type?.toLowerCase() || '';
    const sector = (holding.security?.sector || '').toLowerCase();
    
    // First check the security type field if available
    if (securityType === 'mutual_fund' || sector === 'mutual fund') {
      return 'Mutual Funds';
    }
    if (securityType === 'option' || sector === 'options') {
      return 'Options';
    }
    if (securityType === 'fixed_income' || sector === 'fixed income') {
      return 'Fixed Income';
    }
    
    // Check for mutual funds - specific fund symbols or explicit fund names
    if (symbol === 'VTSAX' || symbol === 'VFIAX' || symbol === 'VTSMX' ||
        symbol === 'FXAIX' || symbol === 'SWTSX' ||
        description.includes('index fund') || description.includes('mutual fund') ||
        description.includes('vanguard total') || description.includes('fidelity 500')) {
      return 'Mutual Funds';
    }
    
    // Check for options - symbol patterns with date and C/P for call/put
    if (symbol.length > 8 && /\d{6}[CP]\d+/.test(symbol)) {
      return 'Options';
    }
    
    // Check for fixed income - bonds, treasuries, CDs
    if (description.includes('bond') || description.includes('treasury') || 
        description.includes(' note ') || description.includes('certificate of deposit')) {
      return 'Fixed Income';
    }
    
    // Check for annuities
    if (description.includes('annuity')) {
      return 'Annuities';
    }
    
    // Default to Equities for stocks - most common case
    return 'Equities';
  };

  // Calculate dynamic data from accountData
  const portfolioData = useMemo(() => {
    if (!accountData) {
      return null;
    }
    
    // If no balances, create default balances
    const balances = accountData.balances || {
      cash: 0,
      margin: 0,
      buyingPower: 0,
      totalValue: 0,
      investedValue: 0,
      realizedGL: 0,
      lastUpdated: new Date().toISOString()
    };

    // Get holdings with full details first
    const holdingsWithDetails = getHoldingsWithDetails();
    
    // Use balances.totalValue from account data to match client dashboard
    // This ensures consistency between dashboard and account page
    const totalValue = balances.totalValue || 0;
    const investedValue = balances.investedValue || 0;
    
    // Calculate unrealized G/L from balances (totalValue - investedValue)
    // This matches what's stored in the account data and ensures consistency
    const totalUnrealizedGL = totalValue - investedValue;
    const totalUnrealizedGLPercent = investedValue > 0 ? (totalUnrealizedGL / investedValue) * 100 : 0;
    
    // Calculate today's unrealized G/L (current price vs previous close)
    const todaysUnrealizedGL = holdingsWithDetails.reduce((sum, holding) => {
      const dayChange = holding.marketData?.dayChange || 0;
      return sum + (holding.quantity * dayChange);
    }, 0);
    const todaysUnrealizedGLPercent = totalValue > 0 ? (todaysUnrealizedGL / totalValue) * 100 : 0;

    // Calculate asset allocation from holdings by asset type
    const assetAllocation = holdingsWithDetails.reduce((acc, holding) => {
      const marketValue = holding.marketValue || 0;
      const assetType = getAssetType(holding);
      const existing = acc.find(item => item.name === assetType);
      if (existing) {
        existing.value += marketValue;
      } else {
        acc.push({
          name: assetType,
          value: marketValue,
          color: getAssetTypeColor(assetType)
        });
      }
      return acc;
    }, [] as Array<{ name: string; value: number; color: string }>);

    // Ensure we have valid numbers
    const safeTotalUnrealizedGL = isNaN(totalUnrealizedGL) ? 0 : totalUnrealizedGL;
    const safeTotalUnrealizedGLPercent = isNaN(totalUnrealizedGLPercent) ? 0 : totalUnrealizedGLPercent;
    const safeTodaysUnrealizedGL = isNaN(todaysUnrealizedGL) ? 0 : todaysUnrealizedGL;
    const safeTodaysUnrealizedGLPercent = isNaN(todaysUnrealizedGLPercent) ? 0 : todaysUnrealizedGLPercent;
    const safeTotalValue = isNaN(totalValue) ? 0 : totalValue;
    

    // Format amounts: minus before dollar sign if negative, no plus sign if positive
    const formatGLAmount = (value: number) => {
      const absValue = Math.abs(value);
      const formatted = absValue.toLocaleString('en-US', { minimumFractionDigits: 2 });
      return value < 0 ? `-$${formatted}` : `$${formatted}`;
    };

    return {
      portfolioValue: `$${safeTotalValue.toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      todaysGL: { 
        amount: formatGLAmount(safeTodaysUnrealizedGL),
        percentage: `${safeTodaysUnrealizedGLPercent >= 0 ? '' : '-'}${Math.abs(safeTodaysUnrealizedGLPercent).toFixed(2)}%`,
        isPositive: safeTodaysUnrealizedGL >= 0
      },
      totalGL: { 
        amount: formatGLAmount(safeTotalUnrealizedGL),
        percentage: `${safeTotalUnrealizedGLPercent >= 0 ? '' : '-'}${Math.abs(safeTotalUnrealizedGLPercent).toFixed(2)}%`,
        isPositive: safeTotalUnrealizedGL >= 0
      },
      positions: { 
        long: { amount: `$${safeTotalValue.toLocaleString('en-US', { minimumFractionDigits: 2 })}` }, 
        short: { amount: '$0.00' } 
      },
      availableCash: `$${(balances.cash || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      fdicSweep: '$250,000.00',
      marginBalance: `$${(balances.margin || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      fundsAvailable: `$${(balances.buyingPower || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      totalAccountValue: `$${safeTotalValue.toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      assetAllocation: assetAllocation
        .filter(item => item.value > 0) // Only include segments with actual value
        .map(item => ({
        ...item,
          // Keep actual market values for the pie chart (not percentages)
          // This ensures all segments are visible even if small
          value: item.value
      }))
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [accountData, getHoldingsWithDetails]);

  // Don't block on loading if we have cached data - show data immediately
  if (loading && !accountData) {
    return (
      <div className="rounded-md space-y-4 md:space-y-4">
        {/* Holdings Title Skeleton */}
        <div className="w-full flex justify-between items-center">
          <div className="h-8 w-32 bg-muted rounded animate-pulse"></div>
          <div className="flex items-center space-x-2">
            <div className="h-9 w-20 bg-muted rounded animate-pulse"></div>
            <div className="h-9 w-24 bg-muted rounded animate-pulse"></div>
          </div>
        </div>
        {/* Cards Skeleton */}
        <div className="w-full flex flex-col md:grid md:grid-cols-3 gap-4 md:gap-4">
          <div className="md:col-span-2 h-64 bg-muted rounded animate-pulse"></div>
          <div className="h-64 bg-muted rounded animate-pulse"></div>
        </div>
        {/* Table Skeleton */}
        <div className="h-96 bg-muted rounded animate-pulse"></div>
      </div>
    );
  }

  if (error && !accountData) {
    return <div className="min-h-screen flex items-center justify-center text-red-500">Error loading account data</div>;
  }

  return (
    <div className="rounded-md space-y-4 md:space-y-4">
         {/* Holdings Title and Action Buttons */}
         <div className="w-full flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <div className="w-full sm:w-auto">
              <PageHeading as="h2" className="text-xl sm:text-2xl">Holdings</PageHeading>
            </div>
            <div className="flex items-center space-x-2 w-full sm:w-auto">
              <Button variant="outline">
                <FileText className="mr-2 h-4 w-4" />
                Export
              </Button>
              <Button variant="outline">
                <History className="mr-2 h-4 w-4" />
                View History
              </Button>
            </div>
          </div>
      <div className="w-full flex flex-col lg:grid lg:grid-cols-3 gap-4 lg:gap-4">
        <Card className="lg:col-span-2 min-w-0 flex flex-col items-start overflow-hidden rounded-2xl p-0">
          <div className="flex-1 w-full p-4 sm:p-6 flex flex-col justify-between items-start gap-4 sm:gap-6">
            <div className="w-full flex flex-col gap-4 sm:gap-6">
              {/* Portfolio market value - full width */}
              <div className="flex flex-col items-start gap-1 px-px">
                <div className="text-sm font-medium text-muted-foreground leading-6" style={{ fontFamily: 'var(--font-family, "Inter")' }}>Portfolio market value</div>
                {(() => {
                  const value = portfolioData?.portfolioValue || '$0.00';
                  const match = value.match(/^\$([\d,]+)\.(\d{2})$/);
                  if (match) {
                    return (
                      <h3 className="flex items-start leading-none">
                        <span className="text-xl sm:text-2xl lg:text-3xl font-medium text-foreground tracking-[-0.24px] leading-[28px] sm:leading-[36px] lg:leading-[40px]" style={{ fontFamily: 'var(--font-family-headers, "Source Serif 4")' }}>
                          ${match[1]}.
                        </span>
                        <span className="text-base sm:text-lg lg:text-xl font-medium text-foreground leading-6 flex items-end" style={{ fontFamily: 'var(--font-family, "Inter")', transform: 'translateY(10px)', marginBottom: '10px' }}>
                          {match[2]}
                        </span>
                      </h3>
                    );
                  }
                  return <h3 className="text-xl sm:text-2xl lg:text-3xl font-medium text-foreground">{value}</h3>;
                })()}
              </div>
              
              {/* Metrics grid - 1 column on mobile, 2 columns on larger screens */}
              <div className="w-full grid grid-cols-1 sm:grid-cols-2 gap-x-4 sm:gap-x-6 gap-y-2">
                {/* Left Column */}
                <div className="flex flex-col gap-2">
                  {/* Today's unrealized G/L */}
                  <div className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-1.5">
                    <div className="text-sm font-medium text-muted-foreground leading-6 sm:w-[180px] flex-shrink-0" style={{ fontFamily: 'var(--font-family, "Inter")' }}>Today&apos;s unrealized G/L</div>
                    <div className="text-sm font-medium text-positive-foreground leading-6" style={{ fontFamily: 'var(--font-family, "Inter")' }}>
                      {portfolioData?.todaysGL.amount} ({portfolioData?.todaysGL.percentage})
                    </div>
                  </div>
                  
                  {/* Total unrealized G/L */}
                  <div className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-1.5">
                    <div className="text-sm font-medium text-muted-foreground leading-6 sm:w-[180px] flex-shrink-0" style={{ fontFamily: 'var(--font-family, "Inter")' }}>Total unrealized G/L</div>
                    <div className="text-sm font-medium text-positive-foreground leading-6" style={{ fontFamily: 'var(--font-family, "Inter")' }}>
                      {portfolioData?.totalGL.amount} ({portfolioData?.totalGL.percentage})
                    </div>
                  </div>
                </div>
                
                {/* Right Column */}
                <div className="flex flex-col gap-2">
                  {/* Long market value */}
                  <div className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-1.5">
                    <div className="text-sm font-medium text-muted-foreground leading-6 sm:w-[180px] flex-shrink-0" style={{ fontFamily: 'var(--font-family, "Inter")' }}>Long market value</div>
                    <div className="text-sm font-medium text-foreground leading-6 whitespace-nowrap" style={{ fontFamily: 'var(--font-family, "Inter")' }}>{portfolioData?.positions.long.amount}</div>
                  </div>
                  
                  {/* Short market value */}
                  <div className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-1.5">
                    <div className="text-sm font-medium text-muted-foreground leading-6 sm:w-[180px] flex-shrink-0" style={{ fontFamily: 'var(--font-family, "Inter")' }}>Short market value</div>
                    <div className="text-sm font-medium text-negative-foreground leading-6 whitespace-nowrap" style={{ fontFamily: 'var(--font-family, "Inter")' }}>{portfolioData?.positions.short.amount}</div>
                  </div>
                </div>
              </div>
            </div>
            
            {/* Border separator */}
            <div className="flex items-center justify-center w-full mt-4 mb-0">
              <div className="w-full h-px border-t"></div>
            </div>
            
            {/* Bottom row: Available cash, FDIC Sweep, Margin balance, Funds available, Total account value */}
            <div className="w-full grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4 lg:gap-4 xl:gap-0 rounded-lg">
              <div className="flex flex-col items-start gap-2 sm:gap-4 py-2 sm:py-3 px-0">
                <div className="flex flex-col items-start gap-1 w-full">
                  <div className="text-sm sm:text-sm font-medium text-muted-foreground leading-6 whitespace-nowrap" style={{ fontFamily: 'var(--font-family, "Inter")' }}>Available cash</div>
                  <div className="text-sm sm:text-sm font-medium text-foreground leading-6 break-words" style={{ fontFamily: 'var(--font-family, "Inter")' }}>{portfolioData?.availableCash}</div>
                </div>
              </div>
              <div className="flex flex-col items-start gap-2 sm:gap-4 py-2 sm:py-3 px-0">
                <div className="flex flex-col items-start gap-1 w-full">
                  <div className="text-sm sm:text-sm font-medium text-muted-foreground leading-6 whitespace-nowrap" style={{ fontFamily: 'var(--font-family, "Inter")' }}>FDIC Sweep</div>
                  <div className="text-sm sm:text-sm font-medium text-foreground leading-6 break-words" style={{ fontFamily: 'var(--font-family, "Inter")' }}>{portfolioData?.fdicSweep}</div>
                </div>
              </div>
              <div className="flex flex-col items-start gap-2 sm:gap-4 py-2 sm:py-3 px-0">
                <div className="flex flex-col items-start gap-1 w-full">
                  <div className="text-sm sm:text-sm font-medium text-muted-foreground leading-6 whitespace-nowrap" style={{ fontFamily: 'var(--font-family, "Inter")' }}>Margin balance</div>
                  <div className="text-sm sm:text-sm font-medium text-foreground leading-6 break-words" style={{ fontFamily: 'var(--font-family, "Inter")' }}>{portfolioData?.marginBalance}</div>
                </div>
              </div>
              <div className="flex flex-col items-start gap-2 sm:gap-4 py-2 sm:py-3 px-0">
                <div className="flex flex-col items-start gap-1 w-full">
                  <div className="flex items-center gap-1">
                    <div className="text-sm sm:text-sm font-medium text-muted-foreground leading-6 whitespace-nowrap" style={{ fontFamily: 'var(--font-family, "Inter")' }}>Funds available</div>
                    <TooltipProvider>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <button className="w-3 h-3 sm:w-3.5 sm:h-3.5 rounded flex items-center justify-center hover:bg-accent flex-shrink-0">
                            <Info className="w-3 h-3 sm:w-3.5 sm:h-3.5 text-muted-foreground" />
                          </button>
                        </TooltipTrigger>
                        <TooltipContent>
                          <p>Funds available for withdrawal or trading.</p>
                        </TooltipContent>
                      </Tooltip>
                    </TooltipProvider>
                  </div>
                  <div className="text-sm sm:text-sm font-medium text-foreground leading-6 break-words" style={{ fontFamily: 'var(--font-family, "Inter")' }}>{portfolioData?.fundsAvailable}</div>
                </div>
              </div>
              <div className="flex flex-col items-start gap-2 sm:gap-4 py-2 sm:py-3 px-0">
                <div className="flex flex-col items-start gap-1 w-full">
                  <div className="flex items-center gap-1">
                    <div className="text-sm sm:text-sm font-medium text-muted-foreground leading-6 whitespace-nowrap" style={{ fontFamily: 'var(--font-family, "Inter")' }}>Total account value</div>
                    <TooltipProvider>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <button className="w-3 h-3 sm:w-3.5 sm:h-3.5 rounded flex items-center justify-center hover:bg-accent flex-shrink-0">
                            <Info className="w-3 h-3 sm:w-3.5 sm:h-3.5 text-muted-foreground" />
                          </button>
                        </TooltipTrigger>
                        <TooltipContent>
                          <p>Total value includes cash, investments, and other assets in your account</p>
                        </TooltipContent>
                      </Tooltip>
                    </TooltipProvider>
                  </div>
                  <div className="text-sm sm:text-sm font-medium text-foreground leading-6 break-words" style={{ fontFamily: 'var(--font-family, "Inter")' }}>{portfolioData?.totalAccountValue}</div>
                </div>
              </div>
            </div>
          </div>
          
          {/* Footer with updated timestamp */}
          <div className="w-full px-4 sm:px-6 py-2 border-t flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2 sm:gap-0">
            <div className="flex-1 flex items-center gap-1.5 flex-wrap">
              <div className="text-xs font-normal text-card-foreground leading-5 tracking-[0.12px] break-words">
                Updated {new Date().toLocaleString('en-US', { 
                  month: '2-digit', 
                  day: '2-digit', 
                  year: 'numeric',
                  hour: 'numeric',
                  minute: '2-digit',
                  hour12: true 
                }).replace(',', '')} ET
              </div>
              <button className="w-6 h-6 rounded-lg border bg-background hover:bg-accent flex items-center justify-center flex-shrink-0">
                <RefreshCw className="w-4 h-4 text-foreground" />
              </button>
            </div>
          </div>
        </Card>

        <Card className="px-4 sm:px-6 pt-4 sm:pt-6 pb-3 flex flex-col items-center gap-4 sm:gap-6">
          <div className="w-full flex justify-between items-center">
            <span className="text-xs sm:text-sm font-medium text-card-foreground">Asset allocation</span>
            <button className="text-xs sm:text-sm font-medium text-primary leading-6 tracking-tight hover:underline">Expand view</button>
          </div>
          
          {/* Chart container - centered */}
          <div className="w-full flex items-center justify-center min-h-[160px] sm:min-h-[192px]">
            <DonutChart 
              data={portfolioData?.assetAllocation || []} 
              portfolioValue={portfolioData ? parseFloat(portfolioData.portfolioValue.replace(/[$,]/g, '')) : 0}
            />
          </div>
          
          {/* Legend - centered with flex-wrap */}
          <div className="w-full flex justify-center items-center gap-4 flex-wrap">
            {(portfolioData?.assetAllocation || []).map((item) => (
              <div key={item.name} className="flex items-center gap-1">
                <span className="w-2 h-2 rounded flex-shrink-0" style={{ backgroundColor: item.color }}></span>
                <span className="text-xs font-medium text-card-foreground leading-5 tracking-tight">{item.name}</span>
              </div>
            ))}
          </div>
        </Card>
      </div>
      
       <HoldingsTable 
         onStockClick={handleHoldingClick} 
         holdingsWithDetails={getHoldingsWithDetails()} 
         accountId={accountIdFromParams}
       />
       

      <Drawer direction="right" open={isStockDrawerOpen} onOpenChange={setIsStockDrawerOpen}>
        <DrawerContent className="h-full w-full max-w-2xl flex flex-col bg-card backdrop-blur-lg">
          <DrawerHeader className="p-4 border-b flex items-center">
            <DrawerTitle className="text-lg font-semibold">
               {/* Intentionally empty title */}
            </DrawerTitle>
            <DrawerClose asChild className="ml-auto">
              <Button variant="secondary" className="flex items-center gap-1">
                <span>Close</span>
                <X className="h-6 w-6" />
              </Button>
            </DrawerClose>
          </DrawerHeader>
          <div className="flex-grow overflow-y-auto h-full p-4">
            {selectedSymbolInDrawer && drawerStockData && (
              drawerTradeMode ? (
                <TradeExecutionPanel
                  symbol={selectedSymbolInDrawer}
                  accountId={accountIdFromParams}
                  initialTradeMode={drawerTradeMode}
                  strikePrice={drawerOptionTradeDetails?.strikePrice}
                  optionType={drawerOptionTradeDetails?.optionType}
                  limitPrice={drawerOptionTradeDetails?.price}
                  onClose={handleCloseDrawerTradePanel}
                />
              ) : (
                 <> 
                   <SecurityHeader 
                     symbol={selectedSymbolInDrawer}
                      stock={drawerStockData}
                      isPositive={isDrawerPositive}
                      isWatchlisted={isDrawerWatchlisted}
                     onChangeSymbolClick={() => setIsSearchModalOpen(true)}
                     onAddToWatchlist={handleAddToWatchlistFromDrawer}
                     isDrawer={true}
                   />
                   <div className="mt-4 pt-4 border-t">
                     <StockDetailPanel 
                       symbol={selectedSymbolInDrawer} 
                       onTradeAction={handleTradeActionFromDrawer}
                     />
                   </div>
                 </>
              )
            )}
            {selectedSymbolInDrawer && !drawerStockData && (
                <div className="p-4 text-center text-muted-foreground">
                    Could not load data for symbol: {selectedSymbolInDrawer}
                </div>
            )}
          </div>
        </DrawerContent>
      </Drawer>

      <SearchModal 
        isOpen={isSearchModalOpen} 
        onOpenChange={setIsSearchModalOpen}
        onSelectSymbol={handleSymbolSelectFromSearch}
      />
    </div>
  );
}