'use client'

import { useState, useMemo } from 'react'
// import dynamic from 'next/dynamic'; // Remove dynamic import
import { HoldingsTable } from './HoldingsTable'
import { Card } from '@/components/ui/card'
import { SearchModal } from '@/components/trade/SearchModal'
import { StockDetailPanel } from '@/components/trade/StockDetailPanel'
import { TradeExecutionPanel } from '@/components/trade/TradeExecutionPanel'
// Re-import DonutChart
import { DonutChart } from '@/components/charts/DonutChart'; 
import { Info, X, FileText, History, RefreshCw } from 'lucide-react' // Added FileText, History, RefreshCw
// import { AccountSelectionModal } from '@/components/trade/AccountSelectionModal' // Removed unused import
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import { 
  Drawer, 
  DrawerContent, 
  DrawerHeader,
  DrawerTitle,
  DrawerClose
} from "@/components/ui/drawer"
import { Button } from "@/components/ui/button"
import { OptionTradeDetails } from '@/components/trade/OptionsChainTable'
// import { OptionsChainTable } from '@/components/trade/OptionsChainTable' // Removed unused import
import { STOCK_DATA } from '@/components/trade/StockDetailPanel' // Keep STOCK_DATA if needed
import { SecurityHeader } from '@/components/trade/SecurityHeader'
import { useAccountData } from '@/contexts/AccountDataContext'
import { getChartColorByIndex } from '@/lib/chartColors'


type TradeMode = 'buy' | 'sell' | null
type DrawerOptionTradeDetails = Omit<OptionTradeDetails, 'symbol'>;

interface AccountContentProps {
  accountId: string;
}

export function AccountContent({ accountId }: AccountContentProps) {
  const accountIdFromParams = accountId;
  const { data: accountData, loading, error, getHoldingsWithDetails } = useAccountData();

  const [isSearchModalOpen, setIsSearchModalOpen] = useState(false);
  const [isStockDrawerOpen, setIsStockDrawerOpen] = useState(false);
  const [selectedSymbolInDrawer, setSelectedSymbolInDrawer] = useState<string | null>(null);
  const [drawerTradeMode, setDrawerTradeMode] = useState<TradeMode>(null);
  const [drawerOptionTradeDetails, setDrawerOptionTradeDetails] = useState<DrawerOptionTradeDetails | null>(null);
  const [isDrawerWatchlisted, setIsDrawerWatchlisted] = useState(false);

  const drawerStockData = useMemo(() => {
    if (!selectedSymbolInDrawer) return null;
    
    // Try to get real market data first
    const realMarketData = accountData?.marketData?.find(m => m.symbol === selectedSymbolInDrawer.toUpperCase());
    
    if (realMarketData) {
      // Create StockInfo from real market data
      const stockInfo = {
        name: realMarketData.description || `${selectedSymbolInDrawer.toUpperCase()} Inc.`,
        exchangeInfo: 'Nasdaq • USD',
        price: realMarketData.currentPrice || 0,
        change: realMarketData.dayChange || 0,
        changePercent: realMarketData.dayChangePercent || 0,
        peRatio: 30.5, // Mock PE ratio
        volume: realMarketData.volume || 0,
        chartData: {}, // Will be generated by StockDetailPanel
        marketStats: {
          open: realMarketData.open || 0,
          high: realMarketData.high || 0,
          low: realMarketData.low || 0,
          prevClose: realMarketData.previousClose || 0,
          '52W High': realMarketData.fiftyTwoWeekHigh || 0,
          '52W Low': realMarketData.fiftyTwoWeekLow || 0
        }
      };
      return stockInfo;
    } else {
      // Fallback to mock data if not found
      return STOCK_DATA[selectedSymbolInDrawer.toUpperCase()] || null;
    }
  }, [selectedSymbolInDrawer, accountData?.marketData]);

  const isDrawerPositive = useMemo(() => 
     drawerStockData ? drawerStockData.change >= 0 : false
  , [drawerStockData]);

  const handleHoldingClick = (symbol: string) => {
    setSelectedSymbolInDrawer(symbol);
    setIsStockDrawerOpen(true);
    setDrawerTradeMode(null);
    setDrawerOptionTradeDetails(null);
  };

  const handleSymbolSelectFromSearch = () => {
    setIsSearchModalOpen(false);
  };

  const handleTradeActionFromDrawer = (tradeSymbol: string, action: TradeMode) => {
    setDrawerTradeMode(action);
    setDrawerOptionTradeDetails(null);
  };

  const handleCloseDrawerTradePanel = () => {
    setDrawerTradeMode(null);
    setDrawerOptionTradeDetails(null);
  };

  const handleAddToWatchlistFromDrawer = () => {
    if (!selectedSymbolInDrawer) return;
    setIsDrawerWatchlisted(!isDrawerWatchlisted);
    // TODO: Implement actual API call
  };

  // Helper function to get sector colors using chart color system
  const getSectorColor = (sector: string) => {
    // Map sectors to chart color indices (cycling through 1-6)
    const sectorMap: Record<string, number> = {
      'Technology': 1,
      'Financial Services': 2,
      'Consumer Discretionary': 3,
      'Automotive': 4,
      'Healthcare': 5,
      'Energy': 6,
      'Utilities': 1,
      'Real Estate': 2
    };
    
    const colorIndex = sectorMap[sector] || 1;
    return getChartColorByIndex(colorIndex);
  };

  // Calculate dynamic data from accountData
  const portfolioData = useMemo(() => {
    if (!accountData) {
      return null;
    }
    
    // If no balances, create default balances
    const balances = accountData.balances || {
      cash: 0,
      margin: 0,
      buyingPower: 0,
      totalValue: 0,
      investedValue: 0,
      realizedGL: 0,
      lastUpdated: new Date().toISOString()
    };

    // Get holdings with full details first
    const holdingsWithDetails = getHoldingsWithDetails();
    
    // Calculate total market value from holdings
    const totalMarketValue = holdingsWithDetails.reduce((sum, holding) => sum + (holding.marketValue || 0), 0);
    const totalInvestedValue = holdingsWithDetails.reduce((sum, holding) => sum + (holding.quantity * holding.avgPrice), 0);
    
    // Use calculated values or fall back to account data
    const totalValue = totalMarketValue + (balances.cash || 0);
    const investedValue = totalInvestedValue;
    
    // Calculate unrealized G/L from holdings
    const unrealizedGL = holdingsWithDetails.reduce((sum, holding) => sum + (holding.unrealizedGL || 0), 0);
    const unrealizedGLPercent = investedValue > 0 ? (unrealizedGL / investedValue) * 100 : 0;
    

    // Calculate asset allocation from holdings
    const assetAllocation = holdingsWithDetails.reduce((acc, holding) => {
      const marketValue = holding.marketValue || 0;
      const existing = acc.find(item => item.name === holding.security.sector);
      if (existing) {
        existing.value += marketValue;
      } else {
        acc.push({
          name: holding.security.sector,
          value: marketValue,
          color: getSectorColor(holding.security.sector)
        });
      }
      return acc;
    }, [] as Array<{ name: string; value: number; color: string }>);

    // Ensure we have valid numbers
    const safeUnrealizedGL = isNaN(unrealizedGL) ? 0 : unrealizedGL;
    const safeUnrealizedGLPercent = isNaN(unrealizedGLPercent) ? 0 : unrealizedGLPercent;
    const safeTotalValue = isNaN(totalValue) ? 0 : totalValue;
    

    return {
      portfolioValue: `$${safeTotalValue.toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      todaysGL: { 
        amount: `${safeUnrealizedGL >= 0 ? '+' : ''}$${safeUnrealizedGL.toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 
        percentage: `${safeUnrealizedGLPercent.toFixed(2)}%` 
      },
      totalGL: { 
        amount: `${safeUnrealizedGL >= 0 ? '+' : ''}$${safeUnrealizedGL.toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 
        percentage: `${safeUnrealizedGLPercent.toFixed(2)}%` 
      },
      positions: { 
        long: { amount: `$${safeTotalValue.toLocaleString('en-US', { minimumFractionDigits: 2 })}` }, 
        short: { amount: '$0.00' } 
      },
      availableCash: `$${(balances.cash || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      fdicSweep: '$250,000.00',
      marginBalance: `$${(balances.margin || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      fundsAvailable: `$${(balances.buyingPower || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      totalAccountValue: `$${safeTotalValue.toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      assetAllocation: assetAllocation.map(item => ({
        ...item,
        value: safeTotalValue > 0 ? Math.round((item.value / safeTotalValue) * 100) : 0
      }))
    };
  }, [accountData, getHoldingsWithDetails]);

  if (loading) {
    return (
      <div className="rounded-md space-y-4 md:space-y-4">
        {/* Holdings Title Skeleton */}
        <div className="w-full flex justify-between items-center">
          <div className="h-8 w-32 bg-muted rounded animate-pulse"></div>
          <div className="flex items-center space-x-2">
            <div className="h-9 w-20 bg-muted rounded animate-pulse"></div>
            <div className="h-9 w-24 bg-muted rounded animate-pulse"></div>
          </div>
        </div>
        {/* Cards Skeleton */}
        <div className="w-full flex flex-col md:grid md:grid-cols-3 gap-4 md:gap-4">
          <div className="md:col-span-2 h-64 bg-muted rounded animate-pulse"></div>
          <div className="h-64 bg-muted rounded animate-pulse"></div>
        </div>
        {/* Table Skeleton */}
        <div className="h-96 bg-muted rounded animate-pulse"></div>
      </div>
    );
  }

  if (error || !accountData) {
    return <div className="min-h-screen flex items-center justify-center text-red-500">Error loading account data</div>;
  }

  return (
    <div className="rounded-md space-y-4 md:space-y-4">
         {/* Holdings Title and Action Buttons */}
         <div className="w-full flex justify-between items-center">
            <h2 className="text-2xl font-serif ">Holdings</h2>
            <div className="flex items-center space-x-2">
              <Button variant="secondary">
                <FileText className="mr-2 h-5 w-5" />
                Export
              </Button>
              <Button variant="secondary">
                <History className="mr-2 h-5 w-5" />
                View History
              </Button>
            </div>
          </div>
      <div className="w-full flex flex-col md:grid md:grid-cols-3 gap-4 md:gap-4">
     
        <Card className="md:col-span-2 min-w-0 flex flex-col justify-start items-start overflow-hidden">
          <div className="flex-1 w-full p-4 md:p-6 flex flex-col justify-between items-start">
            <div className="w-full flex justify-between items-end">
              {/* Left side: Portfolio value and G/L */}
              <div className="flex-1 flex flex-col justify-start items-start gap-4">
                <div className="flex flex-col justify-start items-start gap-2">
                  <div className="flex flex-col justify-start items-start gap-1">
                    <div className="text-sm font-medium text-card-foreground">Portfolio market value</div>
                    {(() => {
                      const value = portfolioData?.portfolioValue || '$0.00';
                      const match = value.match(/^\$([\d,]+)\.(\d{2})$/);
                      if (match) {
                        return (
                          <h3 className="flex items-start">
                            <span className="text-2xl font-medium text-foreground">${match[1]}.</span>
                            <span className="text-lg font-medium text-foreground leading-6">{match[2]}</span>
                          </h3>
                        );
                      }
                      return <h3 className="text-2xl font-medium text-foreground">{value}</h3>;
                    })()}
                  </div>
                  <div className="flex flex-col justify-start items-start gap-2">
                    <div className="flex justify-start items-center gap-1.5">
                      <div className="text-sm font-medium text-card-foreground">Today&apos;s unrealized G/L</div>
                      <div className="flex justify-start items-center gap-1">
                        <div className="text-sm font-medium text-positive">
                          {portfolioData?.todaysGL.amount} ({portfolioData?.todaysGL.percentage})
                        </div>
                      </div>
                    </div>
                    <div className="flex justify-center items-center gap-1.5">
                      <div className="text-sm font-medium text-card-foreground">Total unrealized G/L</div>
                      <div className="flex justify-start items-center gap-1">
                        <div className="text-sm font-medium text-positive">
                          {portfolioData?.totalGL.amount} ({portfolioData?.totalGL.percentage})
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              
              {/* Right side: Long and Short market values */}
              <div className="flex flex-col justify-end items-start gap-2">
                <div className="w-full flex justify-between items-center">
                  <div className="flex justify-start items-center gap-4">
                    <div className="text-sm font-medium text-card-foreground">Long market value</div>
                  </div>
                  <div className="text-sm font-medium text-foreground">{portfolioData?.positions.long.amount}</div>
                </div>
                <div className="w-full flex justify-between items-center">
                  <div className="flex justify-start items-center gap-4">
                    <div className="text-sm font-medium text-card-foreground">Short market value</div>
                  </div>
                  <div className="text-sm font-medium text-destructive">{portfolioData?.positions.short.amount}</div>
                </div>
              </div>
            </div>
            
            {/* Border separator */}
            <div className="self-stretch h-px border-t border-border my-4"></div>
            
            {/* Bottom row: Available cash, FDIC Sweep, Margin balance, Funds available, Total account value */}
            <div className="self-stretch rounded-lg border border-border inline-flex justify-between items-center">
              <div className="flex-1 py-3 rounded-lg border-r border-border flex flex-col justify-start items-start gap-4 px-4">
                <div className="flex flex-col justify-start items-start gap-1">
                  <div className="text-sm font-medium text-card-foreground">Available cash</div>
                  <div className="text-sm font-medium text-foreground">{portfolioData?.availableCash}</div>
                </div>
              </div>
              <div className="flex-1 py-3 rounded-lg border-r border-border flex flex-col justify-start items-start gap-4 px-4">
                <div className="flex flex-col justify-start items-start gap-1">
                  <div className="text-sm font-medium text-card-foreground">FDIC Sweep</div>
                  <div className="text-sm font-medium text-foreground">{portfolioData?.fdicSweep}</div>
                </div>
              </div>
              <div className="flex-1 py-3 rounded-lg border-r border-border flex flex-col justify-start items-start gap-4 px-4">
                <div className="flex flex-col justify-start items-start gap-1">
                  <div className="text-sm font-medium text-card-foreground">Margin balance</div>
                  <div className="text-sm font-medium text-foreground">{portfolioData?.marginBalance}</div>
                </div>
              </div>
              <div className="flex-1 py-3 rounded-lg border-r border-border flex flex-col justify-start items-start gap-4 px-4">
                <div className="flex flex-col justify-start items-start gap-1">
                  <div className="flex justify-start items-center gap-1">
                    <div className="text-sm font-medium text-card-foreground">Funds available</div>
                    <TooltipProvider>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <button className="w-3.5 h-3.5 rounded flex items-center justify-center hover:bg-accent">
                            <Info className="w-3 h-3 text-card-foreground" />
                          </button>
                        </TooltipTrigger>
                        <TooltipContent>
                          <p>Funds available for withdrawal or trading.</p>
                        </TooltipContent>
                      </Tooltip>
                    </TooltipProvider>
                  </div>
                  <div className="text-sm font-medium text-foreground">{portfolioData?.fundsAvailable}</div>
                </div>
              </div>
              <div className="flex-1 py-3 rounded-lg flex flex-col justify-start items-start gap-4 px-4">
                <div className="flex flex-col justify-start items-start gap-1">
                  <div className="flex justify-start items-center gap-1">
                    <div className="text-sm font-medium text-card-foreground">Total account value</div>
                    <TooltipProvider>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <button className="w-3.5 h-3.5 rounded flex items-center justify-center hover:bg-accent">
                            <Info className="w-3 h-3 text-card-foreground" />
                          </button>
                        </TooltipTrigger>
                        <TooltipContent>
                          <p>Total value includes cash, investments, and other assets in your account</p>
                        </TooltipContent>
                      </Tooltip>
                    </TooltipProvider>
                  </div>
                  <div className="text-sm font-medium text-foreground">{portfolioData?.totalAccountValue}</div>
                </div>
              </div>
            </div>
          </div>
          
          {/* Footer with updated timestamp */}
          <div className="self-stretch px-6 py-2 border-t border-border flex justify-between items-center">
            <div className="flex-1 flex justify-start items-center gap-1.5">
              <div className="text-xs font-normal text-card-foreground leading-5 tracking-tight">
                Updated {new Date().toLocaleString('en-US', { 
                  month: '2-digit', 
                  day: '2-digit', 
                  year: 'numeric',
                  hour: 'numeric',
                  minute: '2-digit',
                  hour12: true 
                }).replace(',', '')} ET
              </div>
              <button className="w-6 h-6 rounded-lg border border-border hover:bg-accent flex justify-center items-center">
                <RefreshCw className="w-3 h-3 text-foreground" />
              </button>
            </div>
          </div>
        </Card>

        <Card className="px-6 pt-6 pb-3 flex flex-col items-center gap-6">
          <div className="w-full flex justify-between items-center">
            <span className="text-sm font-medium text-card-foreground">Asset allocation</span>
            <button className="text-sm font-medium text-primary leading-6 tracking-tight hover:underline">Expand view</button>
          </div>
          
          {/* Chart container - centered */}
          <div className="w-48 h-48 relative flex items-center justify-center">
            <DonutChart 
              data={portfolioData?.assetAllocation || []} 
              portfolioValue={portfolioData ? parseFloat(portfolioData.portfolioValue.replace(/[$,]/g, '')) : 0}
            />
          </div>
          
          {/* Legend - centered with flex-wrap */}
          <div className="w-full flex justify-center items-center gap-4 flex-wrap">
            {(portfolioData?.assetAllocation || []).slice(0, 2).map((item) => (
              <div key={item.name} className="flex items-center gap-1">
                <span className="w-2 h-2 rounded flex-shrink-0" style={{ backgroundColor: item.color }}></span>
                <span className="text-xs font-medium text-card-foreground leading-5 tracking-tight">{item.name}</span>
              </div>
            ))}
            {(portfolioData?.assetAllocation || []).length > 2 && (
              <div className="text-xs font-medium text-card-foreground leading-5 tracking-tight">
                +{(portfolioData?.assetAllocation || []).length - 2} more
              </div>
            )}
          </div>
        </Card>
      </div>
      
       <HoldingsTable 
         onStockClick={handleHoldingClick} 
         holdingsWithDetails={getHoldingsWithDetails()} 
         accountId={accountIdFromParams}
       />
       

      <Drawer direction="right" open={isStockDrawerOpen} onOpenChange={setIsStockDrawerOpen}>
        <DrawerContent className="h-full w-full max-w-2xl flex flex-col bg-card backdrop-blur-lg">
          <DrawerHeader className="p-4 border-b flex items-center">
            <DrawerTitle className="text-lg font-semibold">
               {/* Intentionally empty title */}
            </DrawerTitle>
            <DrawerClose asChild className="ml-auto">
              <Button variant="secondary" className="flex items-center gap-1">
                <span>Close</span>
                <X className="h-6 w-6" />
              </Button>
            </DrawerClose>
          </DrawerHeader>
          <div className="flex-grow overflow-y-auto h-full p-4">
            {selectedSymbolInDrawer && drawerStockData && (
              drawerTradeMode ? (
                <TradeExecutionPanel
                  symbol={selectedSymbolInDrawer}
                  accountId={accountIdFromParams}
                  initialTradeMode={drawerTradeMode}
                  strikePrice={drawerOptionTradeDetails?.strikePrice}
                  optionType={drawerOptionTradeDetails?.optionType}
                  limitPrice={drawerOptionTradeDetails?.price}
                  onClose={handleCloseDrawerTradePanel}
                />
              ) : (
                 <> 
                   <SecurityHeader 
                     symbol={selectedSymbolInDrawer}
                      stock={drawerStockData}
                      isPositive={isDrawerPositive}
                      isWatchlisted={isDrawerWatchlisted}
                     onChangeSymbolClick={() => setIsSearchModalOpen(true)}
                     onAddToWatchlist={handleAddToWatchlistFromDrawer}
                     isDrawer={true}
                   />
                   <div className="mt-4 pt-4 border-t">
                     <StockDetailPanel 
                       symbol={selectedSymbolInDrawer} 
                       onTradeAction={handleTradeActionFromDrawer}
                     />
                   </div>
                 </>
              )
            )}
            {selectedSymbolInDrawer && !drawerStockData && (
                <div className="p-4 text-center text-muted-foreground">
                    Could not load data for symbol: {selectedSymbolInDrawer}
                </div>
            )}
          </div>
        </DrawerContent>
      </Drawer>

      <SearchModal 
        isOpen={isSearchModalOpen} 
        onOpenChange={setIsSearchModalOpen}
        onSelectSymbol={handleSymbolSelectFromSearch}
      />
    </div>
  );
}